// EF Core entity for workflow builder run lifecycle records.

namespace DBAIAzure.Storage.Entities;

/// <summary>
/// Persisted representation of a workflow builder run. One row per run;
/// updated on every status transition so the DB always reflects the current state.
/// Maps to the <c>WorkflowBuilderRuns</c> table.
/// </summary>
public sealed class WorkflowRunEntity
{
    /// <summary>Stable run identifier — never generated by the DB; assigned by the orchestrator.</summary>
    public string RunId { get; set; } = string.Empty;

    /// <summary>Workflow definition that produced the run.</summary>
    public Guid WorkflowId { get; set; }

    /// <summary>Display name of the workflow at run creation time.</summary>
    public string WorkflowName { get; set; } = string.Empty;

    /// <summary>Lifecycle status stored as its integer ordinal for compact storage.</summary>
    public int Status { get; set; }

    /// <summary>Identity of the user or process that triggered the run.</summary>
    public string TriggeredBy { get; set; } = string.Empty;

    public DateTimeOffset StartedAt { get; set; }
    public DateTimeOffset? SuspendedAt { get; set; }
    public DateTimeOffset? ResumedAt { get; set; }
    public DateTimeOffset? CompletedAt { get; set; }

    /// <summary>Human-readable failure reason; null for non-failed runs.</summary>
    public string? FailureReason { get; set; }

    /// <summary>Cascade-delete target: execution events owned by this run.</summary>
    public List<WorkflowExecutionEventEntity> ExecutionEvents { get; set; } = new();
}
