namespace DBAIAzure.Core.Models;

/// <summary>
/// Immutable snapshot of a ticket's state as it flows through the intake pipeline.
/// Every mutation produces a new record via C# 'with' expressions — never mutated in place.
/// </summary>
public record TicketState
{
    // ── Identity ───────────────────────────────────────────────────────────────

    public required string TicketId { get; init; }
    public required string Title { get; init; }
    public required string Description { get; init; }

    // ── Source metadata ────────────────────────────────────────────────────────

    /// <summary>"manual" (web form) or "servicenow" (webhook intake).</summary>
    public string Source { get; init; } = "manual";

    /// <summary>ServiceNow internal sys_id — used to write status back to SNow after processing.</summary>
    public string? SnowSysId { get; init; }

    /// <summary>Human-readable ServiceNow incident number, e.g. INC0012345.</summary>
    public string? SnowNumber { get; init; }

    /// <summary>ServiceNow priority label, e.g. "1 - Critical".</summary>
    public string? SnowPriority { get; init; }

    /// <summary>ServiceNow category or service, e.g. "Software" or "Database".</summary>
    public string? SnowCategory { get; init; }

    // ── HITL / clarification ───────────────────────────────────────────────────

    /// <summary>Questions generated by GapAnalysisStep and shown to the PO.</summary>
    public IReadOnlyList<string> ClarifyingQuestions { get; init; } = [];

    /// <summary>PO answer from the HITL panel; appended to the next validation round.</summary>
    public string? HumanAnswer { get; init; }

    /// <summary>Number of clarification rounds completed (capped at 3 before Blocked).</summary>
    public int ClarificationRound { get; init; }

    // ── Estimation ─────────────────────────────────────────────────────────────

    /// <summary>Fibonacci story points assigned by EstimationStep.</summary>
    public int? StoryPoints { get; init; }

    /// <summary>One-sentence reasoning anchoring the estimate to a known reference task.</summary>
    public string? EstimationReasoning { get; init; }

    // ── Actions ────────────────────────────────────────────────────────────────

    /// <summary>Jira issue URL produced by ActionStep (mocked until real connector is wired).</summary>
    public string? JiraIssueUrl { get; init; }
}
